{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.joshuatam",
    "module": "javasteam",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "javasteam-1.8.1.jar",
          "url": "javasteam-1.8.1.jar",
          "size": 16417298,
          "sha512": "599e0641126300d536c08837570dd02a2f0e0c97987b9fbb6187869683dea1126f7036437cbaf8711216a2705e4669fd95385e901a46014e7f88874dbf1e968c",
          "sha256": "38635cb67abfa3bb3e0c8c6ea1b411f9e90c7708fb40c211930541a898a22248",
          "sha1": "a74eeb891e9dda1088433f91d428e9ca06570395",
          "md5": "8616b7fc090b2478b41da1be21ae1f4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-coroutines",
          "version": {
            "requires": "5.3.2"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.20.0"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "javasteam-1.8.1.jar",
          "url": "javasteam-1.8.1.jar",
          "size": 16417298,
          "sha512": "599e0641126300d536c08837570dd02a2f0e0c97987b9fbb6187869683dea1126f7036437cbaf8711216a2705e4669fd95385e901a46014e7f88874dbf1e968c",
          "sha256": "38635cb67abfa3bb3e0c8c6ea1b411f9e90c7708fb40c211930541a898a22248",
          "sha1": "a74eeb891e9dda1088433f91d428e9ca06570395",
          "md5": "8616b7fc090b2478b41da1be21ae1f4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "javasteam-1.8.1-sources.jar",
          "url": "javasteam-1.8.1-sources.jar",
          "size": 4039425,
          "sha512": "f35c712842bad279e54ce5ddf8f3f89fe93dec712450f482c250289e135ff8b143da398513a4b8ac000f712ba091ceb3e6b95081fd7742ecaa98057a8b62154b",
          "sha256": "1d04e28940403b2d91cc95c01dfdb473c01090bd0bc026c4a53c766d773469a3",
          "sha1": "e13c62edee696c45bdbfc0701c805375c570202f",
          "md5": "a87eae35cd2f0801295f93dd3d26b191"
        }
      ]
    }
  ]
}
