{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.joshuatam",
    "module": "javasteam-depotdownloader",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "javasteam-depotdownloader-1.8.1.jar",
          "url": "javasteam-depotdownloader-1.8.1.jar",
          "size": 225371,
          "sha512": "e0ef237a2c30d8417e1f8cdbe4213c505513ad7f1de6dfea15a00549235fdd0e34c1996931052871e66f109abc9fd5a34f7df821a0d6823332205128943606cf",
          "sha256": "3c3e5f49959ec355beb011837d5487f3affde8018f4f07b3b3d478f011112a83",
          "sha1": "ff059087f28a6ed50465abe2665af8305b553480",
          "md5": "5c91a743ee07c926b25912a12cac0800"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.joshuatam",
          "module": "javasteam",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "files": [
        {
          "name": "javasteam-depotdownloader-1.8.1.jar",
          "url": "javasteam-depotdownloader-1.8.1.jar",
          "size": 225371,
          "sha512": "e0ef237a2c30d8417e1f8cdbe4213c505513ad7f1de6dfea15a00549235fdd0e34c1996931052871e66f109abc9fd5a34f7df821a0d6823332205128943606cf",
          "sha256": "3c3e5f49959ec355beb011837d5487f3affde8018f4f07b3b3d478f011112a83",
          "sha1": "ff059087f28a6ed50465abe2665af8305b553480",
          "md5": "5c91a743ee07c926b25912a12cac0800"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "javasteam-depotdownloader-1.8.1-sources.jar",
          "url": "javasteam-depotdownloader-1.8.1-sources.jar",
          "size": 33146,
          "sha512": "a33c4df30697d2198c39b1561c4cce6d92519eeb3c1a3c08c81fe26b77a0443e61e5736b985ab65c696209e52da0d0f085946fce24c7fbb75a984c2fc30ca3f9",
          "sha256": "b8b90e7a4c160e63243b8a3df2102628dac821f98d4827d50557d60805e06fa3",
          "sha1": "8646016890c3b501779a7594280c496749de0ef6",
          "md5": "5cfc3c304c6e2f730988e70e21f339b4"
        }
      ]
    }
  ]
}
